name: weekly-chores

services:
  database:
    build: ./database
    restart: always
    ports:
      - 0.0.0.0:5433:5432
    environment:
      - POSTGRES_PASSWORD=appleseed
      - TZ=America/Edmonton
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    build: ./pgadmin
    restart: always
    ports:
      - 0.0.0.0:15432:80
    depends_on:
      - database
    environment:
      - TZ=America/Edmonton


  api:
    build: ./backend
    ports:
      - 0.0.0.0:8000:8000
    depends_on:
      - database

    environment:
      - DB_USER=postgres
      - DB_HOST=host.docker.internal # host.docker.internal
      - DB_NAME=weekly-chores
      - DB_PASSWORD=appleseed
      - DB_PORT=5433
      - API_URL=http://api
      - TZ=America/Edmonton


  frontend:
    build: ./frontend
    ports:
      - 0.0.0.0:3000:3000
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
      - TZ=America/Edmonton


volumes:
  db-data: