FROM dpage/pgadmin4:latest

ENV PGADMIN_DEFAULT_EMAIL=postgres@omni.com
ENV PGADMIN_DEFAULT_PASSWORD=omni

# Make port 80 available to the world outside this container
EXPOSE 80

# Instructions to run (END HERE)
# docker build -t weekly-chores-database-interface:1.0 database_interface/.
# docker run --network weekly-chores-network --name weekly-chores-database-interface -p 15432:80 -d weekly-chores-database-interface:1.0