services:
  jenkins:
    build: .
    privileged: true
    user: root
    environment:
      - TZ=America/Edmonton
    ports:
    - 8080:8080
    - 50000:50000
    # container_name: jenkins
    volumes:
    - jenkins-volume:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-volume: